INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('04/03/2019', 'Carnaval', 'FACULTATIVO', 'Ponto Facultativo, ou seja, cabe às empresas e orgão públicos decidirem se trabalharão ou não.', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('05/03/2019', 'Carnaval', 'FACULTATIVO', 'Carnaval NÃO é um feriado oficial, é Ponto Facultativo, ou seja, cabe às empresas e orgão públicos decidirem se trabalharão ou não.', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('06/03/2019', 'Carnaval', 'FACULTATIVO', 'Ponto Facultativo até às 14h.', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('20/06/2019', 'Corpus Christi', 'FACULTATIVO', 'Ponto Facultativo no País, mas Feriado Municipal em algumas cidades.. Corpus Christi, expressão latina que significa Corpo de Cristo, é uma festa Cristã realizada na quinta-feira seguinte ao domingo da Santíssima Trindade.', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('15/10/2019', 'Dia do Professor', 'FACULTATIVO', 'FERIADO ESCOLAR - No dia 15 de outubro de 1827 (dia consagrado à educadora Santa Teresa de Ávila), o Imperador do Brasil, Pedro I, baixou um Decreto Imperial que criou o Ensino Elementar no Brasil. Pelo decreto, "todas as cidades, vilas e lugarejos teriam suas escolas de primeiras letras"', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('28/10/2019', 'Dia do Servidor Público', 'FACULTATIVO', 'O dia do servidor público é feriado apenas para funcionários públicos.', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('28/10/2019', 'Ponto Facultativo Municipal', 'FACULTATIVO', 'Dia do Servidor Público - art. 249 da Lei Municipal nº 2.215/1991', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('29/03/2019', 'Aniversário da Ciadade', 'FACULTATIVO', 'Fundação de Curitiba - Aniversário da Cidade (Ponto Facultativo), conforme Lei Municipal nº229,26/12/49', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('24/12/2019', 'Facultativo', 'FACULTATIVO', 'Véspera do Natal', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('20/11/2019', 'Dia da Consciência Negra', 'FACULTATIVO', 'Lei Municipal Nº 1792/2009', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('08/12/2019', 'Ponto Facultativo', 'FACULTATIVO', 'Nossa Senhora da Conceição', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('31/10/2019', 'Dia do Evangélico', 'FACULTATIVO', 'Dia do Evangélico', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('19/03/2019', 'Dia de São José', 'FACULTATIVO', 'Padroeiro do Estado do Ceará', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('26/07/2019', 'Fundação da Cidade de Goiás', 'FACULTATIVO', 'Feriado para Servidores Públicos. Determinado pelo Estatuto dos Funcionários Públicos Civis do Estado de Goiás e de suas Autarquias, Lei nº 10.460, de 22 de fevereiro de 1988', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('24/10/2019', 'Pedra fundamental de Goiânia', 'FACULTATIVO', 'Feriado para Servidores Públicos. Determinado pelo Estatuto dos Funcionários Públicos Civis do Estado de Goiás e de suas Autarquias, Lei nº 10.460, de 22 de fevereiro de 1988', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('05/03/2019', 'Terça de Carnaval', 'FACULTATIVO', 'Feriado apenas no Comércio, segundo Lei nº 5913, de 21 de junho de 1991', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('21/06/2019', 'Facultativo', 'FACULTATIVO', 'Ponto facultativo', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('14/01/2019', 'Véspera de feriado', 'FACULTATIVO', 'Véspera do aniversário da cidade (Ponto Facultativo a Compensar)', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('18/04/2019', 'Quinta-feira Santa', 'FACULTATIVO', 'Ponto facultativo a compensar, a partir de 12:00', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('14/06/2019', 'Pós-feriado', 'FACULTATIVO', 'Pós-feriado de Santo Antônio do Boqueirão (a compensar)', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('28/10/2019', 'Servidor Público', 'FACULTATIVO', 'Comemoração ao Dia do Servidor Público Municipal', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('24/12/2019', 'Véspera de Natal', 'FACULTATIVO', 'Ponto facultativo a partir de 12:00 (a compensar)', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('28/02/2019', 'Facultativo', 'FACULTATIVO', 'aniversário de morte de José Pedro Dias, fundador de Juara', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('18/04/2019', 'Facultativo', 'FACULTATIVO', 'Ponto facultativo a partir das 13h00', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('28/10/2019', 'Servidor público', 'FACULTATIVO', 'Ponto facultativo, Dia do Servidor Público', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('21/06/2019', 'Pós Corpus Christi', 'FACULTATIVO', 'Data após Corpus Christi', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('08/12/2019', 'Dia da Imaculada Conceição', 'FACULTATIVO', 'Dia da Imaculada Conceição, padroeira da cidade', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('08/12/2019', 'N. Sra. da Conceição', 'FACULTATIVO', 'Nossa Senhora da Conceição', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('04/03/2019', 'Segunda de Carnaval', 'FACULTATIVO', 'Ponto Facultativo nas repartições públicas', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('06/03/2019', 'Quarta Feira de Cinzas', 'FACULTATIVO', 'Ponto Facultativo nas repartições públicas', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('31/12/2019', 'Após o meio-dia, Véspera de Ano Novo', 'FACULTATIVO', 'De acordo com o Decreto nº 18882-E de 01 de junho de 2015', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('14/06/2019', 'Ponto facultativo', 'FACULTATIVO', 'Ponto facultativo', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('19/03/2019', 'São José', 'FACULTATIVO', 'Dia de São José padroeiro de Mafra', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('04/03/2019', 'Facultativo', 'FACULTATIVO', 'ponto facultativo do Carnaval', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('05/03/2019', 'Facultativo', 'FACULTATIVO', 'Facultativo', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('14/10/2019', 'Facultativo', 'FACULTATIVO', 'ponto facultativo apenas para a educação, antecipando o feriado escolar do dia 15/10 dia do professor', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('28/10/2019', 'Serv. Público', 'FACULTATIVO', 'Dia do Servidor Público (ponto facultativo)', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('04/03/2019', 'Véspera de Carnaval', 'FACULTATIVO', 'Ponto facultativo', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('18/04/2019', 'Quinta-feira santa', 'FACULTATIVO', 'Quinta-feira santa, ponto facultativo', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('30/06/2019', 'Emancipação', 'FACULTATIVO', 'Emancipação político-administrativa do município', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('20/11/2019', 'Consciência Negra', 'FACULTATIVO', 'Dia da Consciência Negra. Ponto Facultativo de acordo com a Lei Municipal 2484/2008', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('06/03/2019', 'Quarta-feira de cinzas', 'FACULTATIVO', 'Quarta-feira de cinzas, ponto facultativo, expediente a partir das 12h', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('08/07/2019', 'Facultativo', 'FACULTATIVO', 'Facultativo', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('28/10/2019', 'Facultativo', 'FACULTATIVO', 'Facultativo', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('26/12/2019', 'Facultativo', 'FACULTATIVO', 'Facultativo', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('31/12/2019', 'Facultativo', 'FACULTATIVO', 'Facultativo', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('29/06/2019', 'São Pedro', 'FACULTATIVO', '', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('14/01/2019', 'Ponto Facultativo', 'FACULTATIVO', '', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('21/06/2019', 'Ponto Facultativo', 'FACULTATIVO', '', '', '');
INSERT INTO feriados (data, nome, tipo, descricao, uf, municipio) VALUES ('08/07/2019', 'Ponto facultativo', 'FACULTATIVO', '', '', '');
